url: ""
baseurl: ""
title: "4v0v's website"


# title: 4v0v
# baseurl: 
# url: https://4v0v.github.io
# markdown: kramdown
# highlighter: rouge
# kramdown:
#   parse_block_html: true
# sass:
#   style: compressed
# plugins:

# navigation:
#   - text: Acceuil
#     url: /
#     urlwithouthtml: /
#   - text: Articles
#     url: /articles.html
#     urlwithouthtml: /articles
#   - text: Liens
#     url: /liens.html
#     urlwithouthtml: /liens
#   - text: Art
#     url: /art.html
#     urlwithouthtml: /art